#ifndef __FPGA_CTRL_H__
#define __FPGA_CTRL_H__

typedef enum
{
    OPCODE_NET0_FPGA_UPDATE_OFF = 0,
    OPCODE_NET0_SPEED_10M,
    OPCODE_NET0_FPGA_UPDATE_ON,
    OPCODE_NET0_SPEED_100M,
    OPCODE_NET0_NONE,
    OPCODE_NET0_SPEED_1000M,
    OPCODE_NET0_FILTER_ON,
    OPCODE_NET0_FILTER_OFF,
    OPCODE_NET1_FPGA_UPDATE_OFF,
    OPCODE_NET1_SPEED_10M,
    OPCODE_NET1_FPGA_UPDATE_ON,
    OPCODE_NET1_SPEED_100M,
    OPCODE_NET1_NONE,
    OPCODE_NET1_SPEED_1000M,
    OPCODE_NET1_FILTER_ON,
    OPCODE_NET1_FILTER_OFF
}fpgaOperateCode;

extern void fpgaCtrlInit(void);

extern void fpgaCtrl (fpgaOperateCode code);


#endif /*__FPGA_CTRL_H__*/
